CREATE SCHEMA tdlist DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS tdlist.user
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS tdlist.taskList
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id)
  REFERENCES tdlist.user(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS tdlist.task
(
  id INT PRIMARY KEY AUTO_INCREMENT ,
  name VARCHAR(64) NOT NULL,
  deadline DATE,
  taskList_id INT NOT NULL,
  FOREIGN KEY (taskList_id)
  REFERENCES tdlist.taskList(id) ON DELETE CASCADE ON UPDATE CASCADE
);