CREATE SCHEMA tdlist DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS tdlist.user
(
  id VARCHAR(64) PRIMARY KEY,
  email VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS tdlist.taskList
(
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  user_id VARCHAR(64) NOT NULL,
  FOREIGN KEY (user_id)
  REFERENCES tdlist.user(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS tdlist.task
(
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  taskDate DATE,
  taskList_id VARCHAR(64) NOT NULL,
  FOREIGN KEY (taskList_id)
  REFERENCES tdlist.taskList(id) ON DELETE CASCADE ON UPDATE CASCADE
);